### ISSUE TITLE
Re-Implement working NoParallelExecution

### ISSUE THREAD

**Issue by michaelschnyder** [jobbrIO/jobbr-server#42]
Applies to the following situation

Trigger has a Cron Definition of * * * * and a raises a jobrun at 12:00 which takes 5 mins.
Without NoParallelExecution, the trigger would again raise a jobRun at 12:01 even if the previous job did no complete.

-> NoParallelExecution does therefore prevent the trigger from triggering a new jobRun, but does not prevent other triggers from triggering a job.

**Comment by michaelschnyder** [comment]
I suggest to rename this feature to **PreventJobRunDublication** or use an enum `JobRunDublication` with (Ignore, Prevent)

@olibanjoli

**Comment by olibanjoli** [comment]
Duplication ;-)
Mhm I don't like the new name too much yet.

- ParallelExecution is a widely used term which is clear to everyone
- JobRunDuplication lacks the time component
- "Duplication of job runs" is a bit off to me since the feature is about blocking running something in parallel.

I'm sure there is a better name than NoParallelExecution.

Maybe
- DontTriggerIfPreviousDidNotFinish
- WaitForPrevious
- WaitForPreviousToFinish
- DisableConcurrency

**Comment by michaelschnyder** [comment]
So we decided to stick with this name for now, but have also discussed that we should extend the feature so that no other trigger (independent which type) can schedule a new run. Then it would be an update to the Job itself. See #46
